[package]
name = "emlrust"
version = "0.1.0"
edition = "2025"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
dotenv = "0.15.0"
walkdir = "2.3"
regex = "1.9"
scraper = "0.17"
html5ever = "0.26"
mail-parser = "0.8"
dirs = "5.0"
